language: node_js
node_js:
  - 12

before_script:
  - npm run setup
  - npm install -g codecov
  - npm run build

script:
  - npm run test:cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
